# TOPSTSCHOOL Sphinx (Documentation) Maintenance Workflow
# =======================================================
#
# Author: Akshay Mestry <xa@mes3.dev>
# Created on: Tuesday, November 05 2024
# Last updated on: Thursday, November 28 2024

name: maintenance
run-name: Started ${{ github.workflow }} workflow before merging

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - '.github/**'
      - 'docs/**'
      - 'requirements*'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    name: check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871
        with:
          fetch-depth: 1
